export const SETUP_UI_URI = "ui://codex-notification-hub/settings-v2.html";

/**
 * A dependency-free MCP Apps component. It never receives or renders existing
 * credentials; submitted values go directly to the local MCP server.
 */
export const setupUiHtml = String.raw`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<style>
:root{color:#172033;background:#fff;font:14px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body{margin:0}.wrap{max-width:640px;padding:24px}.eyebrow{color:#3370ff;font-size:12px;font-weight:700;letter-spacing:.05em;text-transform:uppercase}.head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.head h2{font-size:22px;margin:6px 0}.hint{color:#667085;line-height:1.6;margin:0}.badge{border-radius:999px;background:#f2f4f7;color:#475467;font-size:12px;font-weight:650;padding:6px 9px;white-space:nowrap}.badge.on{background:#ecfdf3;color:#067647}.card{border:1px solid #eaecf0;border-radius:10px;margin-top:18px;padding:16px}.card h3{font-size:15px;margin:0 0 8px}.quick{background:#f5f8ff;border-color:#d8e4ff}.quick code{background:#fff;border:1px solid #d0d5dd;border-radius:5px;color:#1d4ed8;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;padding:2px 5px}.steps{display:grid;gap:8px;margin:12px 0 0;padding:0;list-style:none}.step{display:flex;gap:9px;align-items:flex-start}.number{align-items:center;background:#3370ff;border-radius:50%;color:#fff;display:flex;flex:0 0 20px;font-size:12px;font-weight:700;height:20px;justify-content:center}.row{margin:18px 0}label{display:block;font-weight:650;margin-bottom:7px}.optional{color:#667085;font-weight:400}input{box-sizing:border-box;width:100%;padding:10px 11px;border:1px solid #cbd5e1;border-radius:7px;font:inherit}input:focus{border-color:#3370ff;box-shadow:0 0 0 3px #e0eaff;outline:0}button{border:0;border-radius:7px;padding:10px 14px;background:#3370ff;color:#fff;font:inherit;font-weight:650;cursor:pointer}button.secondary{background:#fff;color:#344054;border:1px solid #cbd5e1}button.danger{color:#b42318;border-color:#fecdca}.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.status{min-height:20px;margin:12px 0 0}.ok{color:#067647}.error{color:#b42318}.privacy{margin-top:18px;padding:12px 14px;background:#f8fafc;border-radius:8px;color:#475467;line-height:1.6}.muted{color:#667085;font-size:13px;line-height:1.55}</style>
</head><body><main class="wrap"><header class="head"><div><div class="eyebrow">Codex Notification Hub</div><h2>飞书通知设置</h2><p class="hint" id="state">正在读取本机设置…</p></div><span class="badge" id="badge">读取中</span></header>
<section class="card quick"><h3>快速打开方式</h3><p class="hint">在消息框中先从 <strong>+</strong> 选择本插件；这一步只会附加插件，不会打开设置。随后发送 <code>配置通知</code> 即可打开此页。它不是 <code>/</code> 命令，也无需输入插件全名。</p><ol class="steps"><li class="step"><span class="number">1</span><span>选择 <strong>Codex Notification Hub</strong>。</span></li><li class="step"><span class="number">2</span><span>输入并发送 <code>配置通知</code>。</span></li><li class="step"><span class="number">3</span><span>仅在此页填写凭据并点击保存。</span></li></ol></section>
<form id="settings" class="card"><h3>飞书连接</h3><p class="muted">使用飞书群自定义机器人提供的 Webhook；建议同时开启并填写签名密钥。</p><div class="row"><label for="webhook">机器人 Webhook URL</label><input id="webhook" type="url" required autocomplete="off" placeholder="https://open.feishu.cn/open-apis/bot/v2/hook/…"></div>
<div class="row"><label for="secret">签名密钥 <span class="optional">（建议填写）</span></label><input id="secret" type="password" autocomplete="new-password" placeholder="在飞书机器人安全设置中取得"></div>
<div class="actions"><button type="submit">保存并启用飞书通知</button><button class="secondary danger" type="button" id="clear">清除本机设置</button></div></form>
<p id="message" class="status" role="status"></p><p class="privacy"><strong>隐私与边界</strong><br>凭据仅保存到本机插件私有目录，文件权限仅限当前用户；页面和保存结果不会回显凭据，也不会写入项目或提交到 GitHub。建议开启 macOS FileVault。</p></main>
<script>
const message=document.getElementById('message'),state=document.getElementById('state'),badge=document.getElementById('badge'),form=document.getElementById('settings');
let nextId=1;const pending=new Map();
function request(method,params){const id=nextId++;window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*');return new Promise((resolve,reject)=>pending.set(id,{resolve,reject}));}
window.addEventListener('message',event=>{const data=event.data;if(!data||data.jsonrpc!=='2.0')return;if(data.id&&pending.has(data.id)){const item=pending.get(data.id);pending.delete(data.id);data.error?item.reject(new Error(data.error.message||'操作失败')):item.resolve(data.result);}});
function setMessage(text,kind){message.textContent=text;message.className='status '+kind;}
function output(result){return result&&result.structuredContent?result.structuredContent:result;}
function showState(result){const enabled=Boolean(result&&result.enabled);badge.textContent=enabled?'已启用':'未配置';badge.className='badge'+(enabled?' on':'');state.textContent=enabled?'飞书通知已启用。已保存的凭据不会在页面中显示。':'尚未配置飞书通知；保存后才会向外发送消息。';}
async function refresh(){try{showState(output(await request('tools/call',{name:'get_notification_settings',arguments:{}})));}catch{badge.textContent='状态未知';badge.className='badge';state.textContent='暂时无法读取设置；仍可填写后保存。';}}
form.addEventListener('submit',async event=>{event.preventDefault();setMessage('正在保存…','');try{const result=output(await request('tools/call',{name:'save_feishu_settings',arguments:{webhookUrl:document.getElementById('webhook').value,signingSecret:document.getElementById('secret').value||undefined}}));document.getElementById('secret').value='';setMessage(result&&result.enabled?'已保存并启用飞书通知。':'保存失败。','ok');await refresh();}catch(error){setMessage(error.message||'保存失败。','error');}});
document.getElementById('clear').addEventListener('click',async()=>{if(!confirm('确定清除本机飞书通知设置吗？'))return;try{await request('tools/call',{name:'clear_notification_settings',arguments:{}});document.getElementById('webhook').value='';document.getElementById('secret').value='';setMessage('已清除，本插件不会再发送飞书通知。','ok');await refresh();}catch(error){setMessage(error.message||'清除失败。','error');}});refresh();
</script></body></html>`;
